FROM --platform=linux/amd64 ubuntu:20.04

# # Install the necessary dependencies
# RUN apt-get update
# RUN apt-get install -y build-essential
# RUN apt-get install -y unzip git wget

# # Install OhMyZsh, Default powerline10k theme, no plugins installed
# RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" && zsh

